exclude_patterns:
  - "**/test/"
  - "**/androidTest/"
  - "**test"

checks:
  similar-code:
    enabled: true
    config:
      threshold: 200
    identical-code:
      enabled: true
      config:
        threshold: 70

  argument-count:
    config:
      threshold: 6
